### ISSUE TITLE
Tracklist from a long audio sample

### ISSUE THREAD

**Issue by SimCo92** [dotX12/ShazamIO#28]
Hi! First of all thanks a lot for making this..
Did you consider to use as input a long audio sample and get back the tracklist? Do you have any idea on how to do it?

**Comment by dotX12** [comment]
@SimCo92, Greetings, need write your service for this task. this task is not solved with the help of shazam, because it will not be able to give 5-10-20 tracks from one large file.

you need to independently cut the file into pieces of 15 seconds (for example) and send it in a loop.
And then take unique ones and here is your decision.

**Comment by SimCo92** [comment]
Do you think this functionality can be implemented here or it is out of the scope and should be kept separated from this python package?

**Comment by dotX12** [comment]
> @dotX12 Do you think this functionality can be implemented here or it is out of the scope and should be kept separated from this python library?

I think this is out of scope for Shazam (since shazam doesn't have this functionality).
